### ISSUE TITLE
Direction Z in stepper check endstop

### ISSUE THREAD

**Issue by MagoKimbra** [Wurstnase/Marlin4Due#28]
Hi, you have forgotten the directional control check on the endstop of z.
if (TEST(out_bits, Z_AXIS)) {  // -direction
        #if HAS_Z_MIN

          #ifdef Z_DUAL_ENDSTOPS

            bool z_min_endstop = READ(Z_MIN_PIN) != Z_MIN_ENDSTOP_INVERTING,
                z2_min_endstop =
                  #if HAS_Z2_MIN
                    READ(Z2_MIN_PIN) != Z2_MIN_ENDSTOP_INVERTING
                  #else
                    z_min_endstop
                  #endif
                ;

            bool z_min_both = z_min_endstop && old_z_min_endstop,
                z2_min_both = z2_min_endstop && old_z2_min_endstop;
            if ((z_min_both || z2_min_both) && current_block->steps[Z_AXIS] > 0) {
              endstops_trigsteps[Z_AXIS] = count_position[Z_AXIS];
              endstop_hit_bits |= BIT(Z_MIN);
              if (!performing_homing || (performing_homing && z_min_both && z2_min_both)) //if not performing home or if both endstops were trigged during homing...
                step_events_completed = current_block->step_event_count;
            }
            old_z_min_endstop = z_min_endstop;
            old_z2_min_endstop = z2_min_endstop;

          #else // !Z_DUAL_ENDSTOPS

            UPDATE_ENDSTOP(z, Z, min, MIN);

          #endif // !Z_DUAL_ENDSTOPS

        #endif // Z_MIN_PIN
      }
      else { // +direction

        #if HAS_Z_MAX

          #ifdef Z_DUAL_ENDSTOPS

            bool z_max_endstop = READ(Z_MAX_PIN) != Z_MAX_ENDSTOP_INVERTING,
                z2_max_endstop =
                  #if HAS_Z2_MAX
                    READ(Z2_MAX_PIN) != Z2_MAX_ENDSTOP_INVERTING
                  #else
                    z_max_endstop
                  #endif
                ;

            bool z_max_both = z_max_endstop && old_z_max_endstop,
                z2_max_both = z2_max_endstop && old_z2_max_endstop;
            if ((z_max_both || z2_max_both) && current_block->steps[Z_AXIS] > 0) {
              endstops_trigsteps[Z_AXIS] = count_position[Z_AXIS];
              endstop_hit_bits |= BIT(Z_MAX);

             // if (z_max_both) SERIAL_ECHOLN("z_max_endstop = true");
             // if (z2_max_both) SERIAL_ECHOLN("z2_max_endstop = true");

              if (!performing_homing || (performing_homing && z_max_both && z2_max_both)) //if not performing home or if both endstops were trigged during homing...
                step_events_completed = current_block->step_event_count;
            }
            old_z_max_endstop = z_max_endstop;
            old_z2_max_endstop = z2_max_endstop;

          #else // !Z_DUAL_ENDSTOPS

            UPDATE_ENDSTOP(z, Z, max, MAX);

          #endif // !Z_DUAL_ENDSTOPS

        #endif // Z_MAX_PIN
      }

**Comment by Wurstnase** [comment]
Yes, I made only a fix for Marlin8bit at the moment. Will fix this also soon.
