### ISSUE TITLE
MultiU24X24toH16 with u_long timer

### ISSUE THREAD

**Issue by Wurstnase** [Wurstnase/Marlin4Due#3]
Hi @nophead, hi @alexborro,

in https://github.com/MarlinFirmware/Marlin/issues/1396 you've talked about fix point notation. I guess my main-problem should be here.

In stepper.cpp my timer is long, because the Sam3x can easily handle this. In some cases the `timer` could be bigger than 24bit.

```
#define MultiU24X24toH16(intRes, longIn1, longIn2) intRes = ((uint64_t)(longIn1) * (longIn2)) >> 24
```
 and

```
block->acceleration_rate = (long)((float)block->acceleration_st * (16777216.0 / (HAL_TIMER_RATE)))
```

where HAL_TIMER_RATE is 42,000,000.

Did you think, this can be easily fixed?

Many thanks in adcance
Nico

**Comment by nophead** [comment]
Not sure it is broken. block->acceleration rate is 8 bits integer, 24 bits
fraction. Is that not sufficient?

If it isn't you need to change the >> 24 and the 16777216.0 to allow more
bits of integer or more bits of fraction but you will also need to change
where it is used.

**Comment by Wurstnase** [comment]
Ok, maybe I understand it now. Maybe...
This could be not the problem. I think this should be a problem at lower speed (if it would be one) and not at high speed.

At the moment I search for an acceration-issue.

The acceleration works until the acceleration ends and the max speed is reached. At this point the speed jumps a bit. I can see and hear it. Any ideas where I need to look at?

**Comment by nophead** [comment]
All the places it sets the timer in stepper.cpp

**Comment by alexborro** [comment]
Nico, change the code to print out the OCR1A (through serial)... as the bot
speed up, it decrease, than keep constant for constant speed and then
increase as the bot slow down.
You'd be able to see any glitch.

Cheers.

Alex.

2015-02-03 9:59 GMT-02:00 Chris <notifications@github.com>:

> All the places it sets the timer in stepper.cpp
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wurstnase/Marlin4Due/issues/3#issuecomment-72638730>.
>



-- 
*"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )*

Alex Borro

**Comment by nophead** [comment]
Is is safe to call print routines from an interrupt? I would think not.

**Comment by alexborro** [comment]
Yes, it is.. I'm doing a new feature and using it a lot for debugging.
Actually exactly as I told him.

Cheers.

Alex.


2015-02-03 12:50 GMT-02:00 Chris <notifications@github.com>:

> Is is safe to call print routines from an interrupt? I would think not.
>
> On 3 February 2015 at 14:48, alexborro <notifications@github.com> wrote:
>
> > Nico, change the code to print out the OCR1A (through serial)... as the
> > bot
> > speed up, it decrease, than keep constant for constant speed and then
> > increase as the bot slow down.
> > You'd be able to see any glitch.
> >
> > Cheers.
> >
> > Alex.
> >
> > 2015-02-03 9:59 GMT-02:00 Chris <notifications@github.com>:
> >
> > > All the places it sets the timer in stepper.cpp
> > >
> > > --
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/Wurstnase/Marlin4Due/issues/3#issuecomment-72638730>.
> >
> > >
> >
> >
> >
> > --
> > *"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
> > aquele que se adapta melhor as mudanças" ( Charles Darwin )*
> >
> > Alex Borro
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Wurstnase/Marlin4Due/issues/3#issuecomment-72662532>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wurstnase/Marlin4Due/issues/3#issuecomment-72662912>.
>



-- 
*"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )*

Alex Borro

**Comment by Wurstnase** [comment]
Sounds good for debugging. 
Do you use any special software to read the values? I think a normal monitor should not work really well?

**Comment by alexborro** [comment]
Nope, just connect to the printer using pronterface.

Check the code bellow, it is placed in the beginning of the ISR:


if (current_block != NULL) {

  SERIAL_ECHO("OCR1A: ");
  SERIAL_ECHOLN(OCR1A);


  // Set directions TO DO This should be done once during init of
trapezoid. Endstops -> interrupt
  out_bits = current_block->direction_bits;
...


It will print out the OCR1A value each time the drivers are pulsed.

Cheers.

Alex.



2015-02-03 13:12 GMT-02:00 Wurstnase <notifications@github.com>:

> Sounds good for debugging.
> Do you use any special software to read the values? I think a normal
> monitor should not work really well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wurstnase/Marlin4Due/issues/3#issuecomment-72666974>.
>



-- 
*"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )*

Alex Borro

**Comment by Wurstnase** [comment]
Some hours later... 
For the Due there is no OCR1A. But I found something for anyone how search also: <a href=https://android.googlesource.com/kernel/lk/+/upstream-master/platform/sam3/drivers/tc/tc.c>tc.c</a>

```
int tc_read_rc(Tc * p_tc, uint32_t ul_channel)
{
	assert(ul_channel <
			(sizeof(p_tc->TC_CHANNEL) / sizeof(p_tc->TC_CHANNEL[0])));
	return p_tc->TC_CHANNEL[ul_channel].TC_RC;
}
```

**Comment by Wurstnase** [comment]
Well, it doesn't work in the interrupt. This will slow down the complete part by factor 10.

**Comment by Wurstnase** [comment]
After a half night of testing.

With a CoreXY you've got 2^16 step with sqrt(2). With a maximum of 2^16/(sqrt(2)) as quadstepping frequency the problem is gone. There could be some variable anywhere which makes the trouble.

I really think that something in the timer calculation in stepper.cpp. The Multi24x24 maybe. The complete timing goes well until the max acc_step_rate goes higher as the nominal_step_rate and acc_step_rate = nominal_step_rate.

Can you explain me the MultiU24x24toH16 at the new timer calculation with numbers?

**Comment by Wurstnase** [comment]
I pictures

```
speed
|		  *****************
|	
|		
|       *				    *
|     *						  *
|   *						    *
| *							      *
_______________________________________________ -> time
```

**Comment by Wurstnase** [comment]
Hi,

I'm not sure what the problem is, but to take a look deeper I made a python-script for a stepper-simulation. The script is really close to the original stepper.cpp and planner.cpp and you can see a graphic which stepper-speed you have while accerate and decelerate.

**Comment by Wurstnase** [comment]
Finally i got it. 
Division is also on the Due to slow!
