### ISSUE TITLE
Possible BUG, on SD Init Command M21

### ISSUE THREAD

**Issue by giutrec** [Wurstnase/Marlin4Due#32]
Hi, 
I've looks a strange behavior when i give a M21 command, marlin puts in high digital pin 10 of Arduiono Due, and isn't impossible puts it to low.

**Comment by Wurstnase** [comment]
There is then something wrong at the init for that pin. There should be a PULLUP(pin, HIGHLOW) and there is a WRITE(pin, HIGHLOW). I will take a look into it and fix this.

**Comment by Wurstnase** [comment]
I don't find an issue. How does this effect anything which I can test?

**Comment by giutrec** [comment]
for test it, you just write M21 command in printer serial shell, it try to initialize SD card and put HIGH a pin number 10
