### ISSUE TITLE
Marlin paused the print for a few seconds 

### ISSUE THREAD

**Issue by svenp** [Wurstnase/Marlin4Due#42]
Marlin is pausing the print for a few seconds after 50 -60 minutes of printing time.
Then you can find in the serial window there is a "k" instead of "ok" 
Marlin is connected to Windows7 with 250000 Baud at programming port.
With marlin 1.02 at Mega2560 there was no Problem with 250000 at Win7.

![marlin_pause](https://cloud.githubusercontent.com/assets/649690/10546235/18620d4a-742d-11e5-899a-3e92d43da7e5.jpg)

**Comment by Wurstnase** [comment]
When you received just a 'k' your cable has an issue. Maybe too long? But it's not an issue from Marlin or Marlin4Due.

I used 250000 baud some time ago, but now I'm on Linux and there is 115200 more stable or common.

**Comment by svenp** [comment]
The cable is new and only 15 or 20cm long, but you are right this could be the problem.
When the print is finished in some hours, i would also try 115200. 
Is it better to use the programming port or the native usb port?

**Comment by Wurstnase** [comment]
Never tried the native port and this should need some modifications in the code.

If you have some issues with a stable connection AND using Repetier Host you could try ```#define NO_TIMEOUTS 1000```.

Your print only go further because Repetier asks every 2 or 3 seconds for the temperature. And then you get the next 'ok'.

**Comment by svenp** [comment]
With 115200 same cable there is no problem. Everithing is working.
