### ISSUE TITLE
SD CARD is inserted, Arduino Due pin d10 will automatically output high

### ISSUE THREAD

**Issue by Sage1978** [Wurstnase/Marlin4Due#43]
Last month found that MOSFET start automatically, find there uninitialized variables, which can cause the system to malfunction insert SD CARD.

Sd2PinMap.h

SS variable has not been initialized

// Note: use hardware SPI only, soft SPI not supported
// uint8_t const SS_PIN = SS;
uint8_t const SS_PIN = SDSS; // FIX D10 OUTPUT ERROR ... 2015/09/19
uint8_t const MOSI_PIN = MOSI;
uint8_t const MISO_PIN = MISO;
uint8_t const SCK_PIN = SCK;

**Comment by Wurstnase** [comment]
Thx
