### ISSUE TITLE
RAMPS_FD_V2 not active even if in Configuration.h

### ISSUE THREAD

**Issue by HakanBastedt** [Wurstnase/Marlin4Due#47]
I couldn't get the right behavior of the RAMPS_FD_V2, it always
behaved like a RAMPS_FD_V1.
It turns out that line 8 in pins_RAMPS_FD.h that reads

#ifdef MB(RAMPS_FD_V1)

works much better when modified to read

#if MB(RAMPS_FD_V1)

**Comment by Wurstnase** [comment]
Thanks
